package logic;
// Generated 15/09/2019 11:45:03 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * AbaaTbEstado generated by hbm2java
 */
public class AbaaTbEstado  implements java.io.Serializable {


     private int estaIdPk;
     private String estaNombre;
     private String estaTipo;
     private Set<SboTbOrdencompra> sboTbOrdencompras = new HashSet<SboTbOrdencompra>(0);
     private Set<SboTbSoliArti> sboTbSoliArtis = new HashSet<SboTbSoliArti>(0);
     private Set<AbaaTbUsuario> abaaTbUsuarios = new HashSet<AbaaTbUsuario>(0);

    public AbaaTbEstado() {
    }

	
    public AbaaTbEstado(int estaIdPk, String estaNombre, String estaTipo) {
        this.estaIdPk = estaIdPk;
        this.estaNombre = estaNombre;
        this.estaTipo = estaTipo;
    }
    public AbaaTbEstado(int estaIdPk, String estaNombre, String estaTipo, Set<SboTbOrdencompra> sboTbOrdencompras, Set<SboTbSoliArti> sboTbSoliArtis, Set<AbaaTbUsuario> abaaTbUsuarios) {
       this.estaIdPk = estaIdPk;
       this.estaNombre = estaNombre;
       this.estaTipo = estaTipo;
       this.sboTbOrdencompras = sboTbOrdencompras;
       this.sboTbSoliArtis = sboTbSoliArtis;
       this.abaaTbUsuarios = abaaTbUsuarios;
    }
   
    public int getEstaIdPk() {
        return this.estaIdPk;
    }
    
    public void setEstaIdPk(int estaIdPk) {
        this.estaIdPk = estaIdPk;
    }
    public String getEstaNombre() {
        return this.estaNombre;
    }
    
    public void setEstaNombre(String estaNombre) {
        this.estaNombre = estaNombre;
    }
    public String getEstaTipo() {
        return this.estaTipo;
    }
    
    public void setEstaTipo(String estaTipo) {
        this.estaTipo = estaTipo;
    }
    public Set<SboTbOrdencompra> getSboTbOrdencompras() {
        return this.sboTbOrdencompras;
    }
    
    public void setSboTbOrdencompras(Set<SboTbOrdencompra> sboTbOrdencompras) {
        this.sboTbOrdencompras = sboTbOrdencompras;
    }
    public Set<SboTbSoliArti> getSboTbSoliArtis() {
        return this.sboTbSoliArtis;
    }
    
    public void setSboTbSoliArtis(Set<SboTbSoliArti> sboTbSoliArtis) {
        this.sboTbSoliArtis = sboTbSoliArtis;
    }
    public Set<AbaaTbUsuario> getAbaaTbUsuarios() {
        return this.abaaTbUsuarios;
    }
    
    public void setAbaaTbUsuarios(Set<AbaaTbUsuario> abaaTbUsuarios) {
        this.abaaTbUsuarios = abaaTbUsuarios;
    }




}


