package logic;
// Generated 15/09/2019 11:45:03 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Catarticulo generated by hbm2java
 */
public class Catarticulo  implements java.io.Serializable {


     private int catIdPk;
     private String catCodSicop;
     private SboTbSubfamilia sboTbSubfamilia;
     private String catDesc;
     private Set<SboTbArticulo> sboTbArticulos = new HashSet<SboTbArticulo>(0);

    public Catarticulo() {
    }

    public String getCatCodSicop() {
        return catCodSicop;
    }

    public void setCatCodSicop(String catCodSicop) {
        this.catCodSicop = catCodSicop;
    }

	
    public Catarticulo(int catIdPk) {
        this.catIdPk = catIdPk;
    }
    public Catarticulo(int catIdPk, SboTbSubfamilia sboTbSubfamilia, String catDesc, Set<SboTbArticulo> sboTbArticulos) {
       this.catIdPk = catIdPk;
       this.sboTbSubfamilia = sboTbSubfamilia;
       this.catDesc = catDesc;
       this.sboTbArticulos = sboTbArticulos;
    }
   
    public int getCatIdPk() {
        return this.catIdPk;
    }
    
    public void setCatIdPk(int catIdPk) {
        this.catIdPk = catIdPk;
    }
    public SboTbSubfamilia getSboTbSubfamilia() {
        return this.sboTbSubfamilia;
    }
    
    public void setSboTbSubfamilia(SboTbSubfamilia sboTbSubfamilia) {
        this.sboTbSubfamilia = sboTbSubfamilia;
    }
    public String getCatDesc() {
        return this.catDesc;
    }
    
    public void setCatDesc(String catDesc) {
        this.catDesc = catDesc;
    }
    public Set<SboTbArticulo> getSboTbArticulos() {
        return this.sboTbArticulos;
    }
    
    public void setSboTbArticulos(Set<SboTbArticulo> sboTbArticulos) {
        this.sboTbArticulos = sboTbArticulos;
    }




}


