package logic;
// Generated 15/09/2019 11:45:03 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * SacProyectos generated by hbm2java
 */
public class SacProyectos  implements java.io.Serializable {


     private int proyIdPk;
     private String proyDesc;
     private Set<SboTbOrdencompra> sboTbOrdencompras = new HashSet<SboTbOrdencompra>(0);

    public SacProyectos() {
    }

	
    public SacProyectos(int proyIdPk, String proyDesc) {
        this.proyIdPk = proyIdPk;
        this.proyDesc = proyDesc;
    }
    public SacProyectos(int proyIdPk, String proyDesc, Set<SboTbOrdencompra> sboTbOrdencompras) {
       this.proyIdPk = proyIdPk;
       this.proyDesc = proyDesc;
       this.sboTbOrdencompras = sboTbOrdencompras;
    }
   
    public int getProyIdPk() {
        return this.proyIdPk;
    }
    
    public void setProyIdPk(int proyIdPk) {
        this.proyIdPk = proyIdPk;
    }
    public String getProyDesc() {
        return this.proyDesc;
    }
    
    public void setProyDesc(String proyDesc) {
        this.proyDesc = proyDesc;
    }
    public Set<SboTbOrdencompra> getSboTbOrdencompras() {
        return this.sboTbOrdencompras;
    }
    
    public void setSboTbOrdencompras(Set<SboTbOrdencompra> sboTbOrdencompras) {
        this.sboTbOrdencompras = sboTbOrdencompras;
    }




}


