package logic;
// Generated 15/09/2019 11:45:03 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * SboTbContable generated by hbm2java
 */
public class SboTbContable  implements java.io.Serializable {


     private String cntIdPk;
     private String cntDesc;
     private Set<SboTbArticulo> sboTbArticulos = new HashSet<SboTbArticulo>(0);

    public SboTbContable() {
    }

	
    public SboTbContable(String cntIdPk) {
        this.cntIdPk = cntIdPk;
    }
    public SboTbContable(String cntIdPk, String cntDesc, Set<SboTbArticulo> sboTbArticulos) {
       this.cntIdPk = cntIdPk;
       this.cntDesc = cntDesc;
       this.sboTbArticulos = sboTbArticulos;
    }
   
    public String getCntIdPk() {
        return this.cntIdPk;
    }
    
    public void setCntIdPk(String cntIdPk) {
        this.cntIdPk = cntIdPk;
    }
    public String getCntDesc() {
        return this.cntDesc;
    }
    
    public void setCntDesc(String cntDesc) {
        this.cntDesc = cntDesc;
    }
    public Set<SboTbArticulo> getSboTbArticulos() {
        return this.sboTbArticulos;
    }
    
    public void setSboTbArticulos(Set<SboTbArticulo> sboTbArticulos) {
        this.sboTbArticulos = sboTbArticulos;
    }




}


