package logic;
// Generated 15/09/2019 11:45:03 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * SboTbFamilia generated by hbm2java
 */
public class SboTbFamilia  implements java.io.Serializable {


     private String famiIdPk;
     private String famiDesc;
     private Set<SboTbSubfamilia> sboTbSubfamilias = new HashSet<SboTbSubfamilia>(0);

    public SboTbFamilia() {
    }

	
    public SboTbFamilia(String famiIdPk) {
        this.famiIdPk = famiIdPk;
    }
    public SboTbFamilia(String famiIdPk, String famiDesc, Set<SboTbSubfamilia> sboTbSubfamilias) {
       this.famiIdPk = famiIdPk;
       this.famiDesc = famiDesc;
       this.sboTbSubfamilias = sboTbSubfamilias;
    }
   
    public String getFamiIdPk() {
        return this.famiIdPk;
    }
    
    public void setFamiIdPk(String famiIdPk) {
        this.famiIdPk = famiIdPk;
    }
    public String getFamiDesc() {
        return this.famiDesc;
    }
    
    public void setFamiDesc(String famiDesc) {
        this.famiDesc = famiDesc;
    }
    public Set<SboTbSubfamilia> getSboTbSubfamilias() {
        return this.sboTbSubfamilias;
    }
    
    public void setSboTbSubfamilias(Set<SboTbSubfamilia> sboTbSubfamilias) {
        this.sboTbSubfamilias = sboTbSubfamilias;
    }




}


