package logic;
// Generated 15/09/2019 11:45:03 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * SboTbSubfamilia generated by hbm2java
 */
public class SboTbSubfamilia  implements java.io.Serializable {


     private String subfamiIdPk;
     private SboTbFamilia sboTbFamilia;
     private String subfamiDesc;
     private Set<Catarticulo> catarticulos = new HashSet<Catarticulo>(0);

    public SboTbSubfamilia() {
    }

	
    public SboTbSubfamilia(String subfamiIdPk) {
        this.subfamiIdPk = subfamiIdPk;
    }
    public SboTbSubfamilia(String subfamiIdPk, SboTbFamilia sboTbFamilia, String subfamiDesc, Set<Catarticulo> catarticulos) {
       this.subfamiIdPk = subfamiIdPk;
       this.sboTbFamilia = sboTbFamilia;
       this.subfamiDesc = subfamiDesc;
       this.catarticulos = catarticulos;
    }
   
    public String getSubfamiIdPk() {
        return this.subfamiIdPk;
    }
    
    public void setSubfamiIdPk(String subfamiIdPk) {
        this.subfamiIdPk = subfamiIdPk;
    }
    public SboTbFamilia getSboTbFamilia() {
        return this.sboTbFamilia;
    }
    
    public void setSboTbFamilia(SboTbFamilia sboTbFamilia) {
        this.sboTbFamilia = sboTbFamilia;
    }
    public String getSubfamiDesc() {
        return this.subfamiDesc;
    }
    
    public void setSubfamiDesc(String subfamiDesc) {
        this.subfamiDesc = subfamiDesc;
    }
    public Set<Catarticulo> getCatarticulos() {
        return this.catarticulos;
    }
    
    public void setCatarticulos(Set<Catarticulo> catarticulos) {
        this.catarticulos = catarticulos;
    }




}


