package logic;
// Generated 15/09/2019 11:45:03 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SboTbOrdencompra generated by hbm2java
 */
public class SboTbOrdencompra  implements java.io.Serializable {


     private int ocIdPk;
     private AbaaTbEstado abaaTbEstado;
     private Date ocFecha;
     private Float ocPrecTota;
     private Integer ocCant;
     private String ocUnidMedi;
     private Integer ocCodi;
     private String ocDesc;
     private Float ocPrecPorArti;
     private String ocMode;
     private String ocSeri;
     private String ocMarc;
     private Set<SacProyectos> sacProyectoses = new HashSet<SacProyectos>(0);
     private Set<SboTbProveedor> sboTbProveedors = new HashSet<SboTbProveedor>(0);
     private Set<SboTbArticulo> sboTbArticulos = new HashSet<SboTbArticulo>(0);

    public SboTbOrdencompra() {
    }

	
    public SboTbOrdencompra(int ocIdPk) {
        this.ocIdPk = ocIdPk;
    }
    public SboTbOrdencompra(int ocIdPk, AbaaTbEstado abaaTbEstado, Date ocFecha, Float ocPrecTota, Integer ocCant, String ocUnidMedi, Integer ocCodi, String ocDesc, Float ocPrecPorArti, String ocMode, String ocSeri, String ocMarc, Set<SacProyectos> sacProyectoses, Set<SboTbProveedor> sboTbProveedors, Set<SboTbArticulo> sboTbArticulos) {
       this.ocIdPk = ocIdPk;
       this.abaaTbEstado = abaaTbEstado;
       this.ocFecha = ocFecha;
       this.ocPrecTota = ocPrecTota;
       this.ocCant = ocCant;
       this.ocUnidMedi = ocUnidMedi;
       this.ocCodi = ocCodi;
       this.ocDesc = ocDesc;
       this.ocPrecPorArti = ocPrecPorArti;
       this.ocMode = ocMode;
       this.ocSeri = ocSeri;
       this.ocMarc = ocMarc;
       this.sacProyectoses = sacProyectoses;
       this.sboTbProveedors = sboTbProveedors;
       this.sboTbArticulos = sboTbArticulos;
    }
   
    public int getOcIdPk() {
        return this.ocIdPk;
    }
    
    public void setOcIdPk(int ocIdPk) {
        this.ocIdPk = ocIdPk;
    }
    public AbaaTbEstado getAbaaTbEstado() {
        return this.abaaTbEstado;
    }
    
    public void setAbaaTbEstado(AbaaTbEstado abaaTbEstado) {
        this.abaaTbEstado = abaaTbEstado;
    }
    public Date getOcFecha() {
        return this.ocFecha;
    }
    
    public void setOcFecha(Date ocFecha) {
        this.ocFecha = ocFecha;
    }
    public Float getOcPrecTota() {
        return this.ocPrecTota;
    }
    
    public void setOcPrecTota(Float ocPrecTota) {
        this.ocPrecTota = ocPrecTota;
    }
    public Integer getOcCant() {
        return this.ocCant;
    }
    
    public void setOcCant(Integer ocCant) {
        this.ocCant = ocCant;
    }
    public String getOcUnidMedi() {
        return this.ocUnidMedi;
    }
    
    public void setOcUnidMedi(String ocUnidMedi) {
        this.ocUnidMedi = ocUnidMedi;
    }
    public Integer getOcCodi() {
        return this.ocCodi;
    }
    
    public void setOcCodi(Integer ocCodi) {
        this.ocCodi = ocCodi;
    }
    public String getOcDesc() {
        return this.ocDesc;
    }
    
    public void setOcDesc(String ocDesc) {
        this.ocDesc = ocDesc;
    }
    public Float getOcPrecPorArti() {
        return this.ocPrecPorArti;
    }
    
    public void setOcPrecPorArti(Float ocPrecPorArti) {
        this.ocPrecPorArti = ocPrecPorArti;
    }
    public String getOcMode() {
        return this.ocMode;
    }
    
    public void setOcMode(String ocMode) {
        this.ocMode = ocMode;
    }
    public String getOcSeri() {
        return this.ocSeri;
    }
    
    public void setOcSeri(String ocSeri) {
        this.ocSeri = ocSeri;
    }
    public String getOcMarc() {
        return this.ocMarc;
    }
    
    public void setOcMarc(String ocMarc) {
        this.ocMarc = ocMarc;
    }
    public Set<SacProyectos> getSacProyectoses() {
        return this.sacProyectoses;
    }
    
    public void setSacProyectoses(Set<SacProyectos> sacProyectoses) {
        this.sacProyectoses = sacProyectoses;
    }
    public Set<SboTbProveedor> getSboTbProveedors() {
        return this.sboTbProveedors;
    }
    
    public void setSboTbProveedors(Set<SboTbProveedor> sboTbProveedors) {
        this.sboTbProveedors = sboTbProveedors;
    }
    public Set<SboTbArticulo> getSboTbArticulos() {
        return this.sboTbArticulos;
    }
    
    public void setSboTbArticulos(Set<SboTbArticulo> sboTbArticulos) {
        this.sboTbArticulos = sboTbArticulos;
    }




}


