package logic;
// Generated 15/09/2019 11:45:03 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * SboTbProveedor generated by hbm2java
 */
public class SboTbProveedor  implements java.io.Serializable {


     private int proveIdProvePk;
     private String proveNomb;
     private String proveCodigo;
     private String proveCedula;
     private int proveTelefono;
     private String proveCorreo;
     private String proveFax;
     private Set<SboTbOrdencompra> sboTbOrdencompras = new HashSet<SboTbOrdencompra>(0);

    public SboTbProveedor() {
    }

    public String getProveCodigo() {
        return proveCodigo;
    }

    public void setProveCodigo(String proveCodigo) {
        this.proveCodigo = proveCodigo;
    }

    public String getProveCedula() {
        return proveCedula;
    }

    public void setProveCedula(String proveCedula) {
        this.proveCedula = proveCedula;
    }

    public int getProveTelefono() {
        return proveTelefono;
    }

    public void setProveTelefono(int proveTelefono) {
        this.proveTelefono = proveTelefono;
    }

    public String getProveCorreo() {
        return proveCorreo;
    }

    public void setProveCorreo(String proveCorreo) {
        this.proveCorreo = proveCorreo;
    }

    public String getProveFax() {
        return proveFax;
    }

    public void setProveFax(String proveFax) {
        this.proveFax = proveFax;
    }

    public SboTbProveedor(int proveIdProvePk, String proveNomb, String proveCodigo, String proveCedula, int proveTelefono, String proveCorreo, String proveFax) {
        this.proveIdProvePk = proveIdProvePk;
        this.proveNomb = proveNomb;
        this.proveCodigo = proveCodigo;
        this.proveCedula = proveCedula;
        this.proveTelefono = proveTelefono;
        this.proveCorreo = proveCorreo;
        this.proveFax = proveFax;
    }

    
	
    public SboTbProveedor(int proveIdProvePk, String proveNomb) {
        this.proveIdProvePk = proveIdProvePk;
        this.proveNomb = proveNomb;
    }
    public SboTbProveedor(int proveIdProvePk, String proveNomb, Set<SboTbOrdencompra> sboTbOrdencompras) {
       this.proveIdProvePk = proveIdProvePk;
       this.proveNomb = proveNomb;
       this.sboTbOrdencompras = sboTbOrdencompras;
    }
   
    public int getProveIdProvePk() {
        return this.proveIdProvePk;
    }
    
    public void setProveIdProvePk(int proveIdProvePk) {
        this.proveIdProvePk = proveIdProvePk;
    }
    public String getProveNomb() {
        return this.proveNomb;
    }
    
    public void setProveNomb(String proveNomb) {
        this.proveNomb = proveNomb;
    }
    public Set<SboTbOrdencompra> getSboTbOrdencompras() {
        return this.sboTbOrdencompras;
    }
    
    public void setSboTbOrdencompras(Set<SboTbOrdencompra> sboTbOrdencompras) {
        this.sboTbOrdencompras = sboTbOrdencompras;
    }




}


