package logic;
// Generated 15/09/2019 11:45:03 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SboTbArticulo generated by hbm2java
 */
public class SboTbArticulo  implements java.io.Serializable {


     private int artIdPk;
     private AbaaTbDepartamento abaaTbDepartamento;
     private Catarticulo catarticulo;
     private SboTbContable sboTbContable;
     private SboTbOrdencompra sboTbOrdencompra;
     private SboTbSoliArti sboTbSoliArti;
     private Float artPrecio;
     private String artCodContGast;
     private String artCodContExis;
     private String artCodContSal;
     private String artDescrip;
     private Date artFvenc;
     private Date artFingr;
     private Date artFsali;
     private Float artMaxi;
     private Float artMini;
     private Byte artEsac;
     private Float artLimiDepa;
     private Float artCantRest;
     private Float artCant;
     private String artMode;
     private String artNumeSeri;
     private String artMarc;
     private String artNumeFact;
     private String artCodiPresup;
     private Set<SboTbExistencia> sboTbExistencias = new HashSet<SboTbExistencia>(0);

    public SboTbArticulo() {
    }

	
    public SboTbArticulo(int artIdPk) {
        this.artIdPk = artIdPk;
    }
    public SboTbArticulo(int artIdPk, AbaaTbDepartamento abaaTbDepartamento, Catarticulo catarticulo, SboTbContable sboTbContable, SboTbOrdencompra sboTbOrdencompra, SboTbSoliArti sboTbSoliArti, Float artPrecio, String artCodContGast, String artCodContExis, String artCodContSal, Date artFvenc, Date artFingr, Date artFsali, Float artMaxi, Float artMini, Byte artEsac, Float artLimiDepa, Float artCantRest, Float artCant, String artMode, String artNumeSeri, String artMarc, String artNumeFact, String artCodiPresup, Set<SboTbExistencia> sboTbExistencias) {
       this.artIdPk = artIdPk;
       this.abaaTbDepartamento = abaaTbDepartamento;
       this.catarticulo = catarticulo;
       this.sboTbContable = sboTbContable;
       this.sboTbOrdencompra = sboTbOrdencompra;
       this.sboTbSoliArti = sboTbSoliArti;
       this.artPrecio = artPrecio;
       this.artCodContGast = artCodContGast;
       this.artCodContExis = artCodContExis;
       this.artCodContSal = artCodContSal;
       this.artFvenc = artFvenc;
       this.artFingr = artFingr;
       this.artFsali = artFsali;
       this.artMaxi = artMaxi;
       this.artMini = artMini;
       this.artEsac = artEsac;
       this.artLimiDepa = artLimiDepa;
       this.artCantRest = artCantRest;
       this.artCant = artCant;
       this.artMode = artMode;
       this.artNumeSeri = artNumeSeri;
       this.artMarc = artMarc;
       this.artNumeFact = artNumeFact;
       this.artCodiPresup = artCodiPresup;
       this.sboTbExistencias = sboTbExistencias;
    }
   
    public int getArtIdPk() {
        return this.artIdPk;
    }
    
    public void setArtIdPk(int artIdPk) {
        this.artIdPk = artIdPk;
    }
    public AbaaTbDepartamento getAbaaTbDepartamento() {
        return this.abaaTbDepartamento;
    }
    
    public void setAbaaTbDepartamento(AbaaTbDepartamento abaaTbDepartamento) {
        this.abaaTbDepartamento = abaaTbDepartamento;
    }
    public Catarticulo getCatarticulo() {
        return this.catarticulo;
    }
    
    public void setCatarticulo(Catarticulo catarticulo) {
        this.catarticulo = catarticulo;
    }
    public SboTbContable getSboTbContable() {
        return this.sboTbContable;
    }
    
    public void setSboTbContable(SboTbContable sboTbContable) {
        this.sboTbContable = sboTbContable;
    }
    public SboTbOrdencompra getSboTbOrdencompra() {
        return this.sboTbOrdencompra;
    }
    
    public void setSboTbOrdencompra(SboTbOrdencompra sboTbOrdencompra) {
        this.sboTbOrdencompra = sboTbOrdencompra;
    }
    public SboTbSoliArti getSboTbSoliArti() {
        return this.sboTbSoliArti;
    }
    
    public void setSboTbSoliArti(SboTbSoliArti sboTbSoliArti) {
        this.sboTbSoliArti = sboTbSoliArti;
    }
    public Float getArtPrecio() {
        return this.artPrecio;
    }
    
    public void setArtPrecio(Float artPrecio) {
        this.artPrecio = artPrecio;
    }
    public String getArtCodContGast() {
        return this.artCodContGast;
    }
    
    public void setArtCodContGast(String artCodContGast) {
        this.artCodContGast = artCodContGast;
    }
    public String getArtCodContExis() {
        return this.artCodContExis;
    }
    
    public void setArtCodContExis(String artCodContExis) {
        this.artCodContExis = artCodContExis;
    }
    public String getArtCodContSal() {
        return this.artCodContSal;
    }
    
    public void setArtCodContSal(String artCodContSal) {
        this.artCodContSal = artCodContSal;
    }
    public Date getArtFvenc() {
        return this.artFvenc;
    }
    
    public void setArtFvenc(Date artFvenc) {
        this.artFvenc = artFvenc;
    }
    public Date getArtFingr() {
        return this.artFingr;
    }
    
    public void setArtFingr(Date artFingr) {
        this.artFingr = artFingr;
    }
    public Date getArtFsali() {
        return this.artFsali;
    }
    
    public void setArtFsali(Date artFsali) {
        this.artFsali = artFsali;
    }
    public Float getArtMaxi() {
        return this.artMaxi;
    }
    
    public void setArtMaxi(Float artMaxi) {
        this.artMaxi = artMaxi;
    }
    public Float getArtMini() {
        return this.artMini;
    }
    
    public void setArtMini(Float artMini) {
        this.artMini = artMini;
    }
    public Byte getArtEsac() {
        return this.artEsac;
    }
    
    public void setArtEsac(Byte artEsac) {
        this.artEsac = artEsac;
    }
    public Float getArtLimiDepa() {
        return this.artLimiDepa;
    }
    
    public void setArtLimiDepa(Float artLimiDepa) {
        this.artLimiDepa = artLimiDepa;
    }
    public Float getArtCantRest() {
        return this.artCantRest;
    }
    
    public void setArtCantRest(Float artCantRest) {
        this.artCantRest = artCantRest;
    }
    public Float getArtCant() {
        return this.artCant;
    }
    
    public void setArtCant(Float artCant) {
        this.artCant = artCant;
    }
    public String getArtMode() {
        return this.artMode;
    }
    
    public void setArtMode(String artMode) {
        this.artMode = artMode;
    }
    public String getArtNumeSeri() {
        return this.artNumeSeri;
    }
    
    public void setArtNumeSeri(String artNumeSeri) {
        this.artNumeSeri = artNumeSeri;
    }
    public String getArtMarc() {
        return this.artMarc;
    }
    
    public void setArtMarc(String artMarc) {
        this.artMarc = artMarc;
    }
    public String getArtNumeFact() {
        return this.artNumeFact;
    }
    
    public void setArtNumeFact(String artNumeFact) {
        this.artNumeFact = artNumeFact;
    }
    public String getArtCodiPresup() {
        return this.artCodiPresup;
    }
    
    public void setArtCodiPresup(String artCodiPresup) {
        this.artCodiPresup = artCodiPresup;
    }
    public Set<SboTbExistencia> getSboTbExistencias() {
        return this.sboTbExistencias;
    }
    
    public void setSboTbExistencias(Set<SboTbExistencia> sboTbExistencias) {
        this.sboTbExistencias = sboTbExistencias;
    }




}


