package logic;
// Generated 15/09/2019 11:45:03 PM by Hibernate Tools 4.3.1



/**
 * Sysdiagrams generated by hbm2java
 */
public class Sysdiagrams  implements java.io.Serializable {


     private Integer diagramId;
     private Integer version;
     private String name;
     private int principalId;
     private byte[] definition;

    public Sysdiagrams() {
    }

	
    public Sysdiagrams(String name, int principalId) {
        this.name = name;
        this.principalId = principalId;
    }
    public Sysdiagrams(String name, int principalId, byte[] definition) {
       this.name = name;
       this.principalId = principalId;
       this.definition = definition;
    }
   
    public Integer getDiagramId() {
        return this.diagramId;
    }
    
    public void setDiagramId(Integer diagramId) {
        this.diagramId = diagramId;
    }
    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public int getPrincipalId() {
        return this.principalId;
    }
    
    public void setPrincipalId(int principalId) {
        this.principalId = principalId;
    }
    public byte[] getDefinition() {
        return this.definition;
    }
    
    public void setDefinition(byte[] definition) {
        this.definition = definition;
    }




}


